name: Android CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Get files from master branch
      - name: Checkout the code
        uses: actions/checkout@v2
        
        # Execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
        #Build the app
      - name: Build the app
        run: ./gradlew build
        
  
  test:
    runs-on: macOS-latest
    needs: [build]
    steps:
    
    - name: checkout
      uses: actions/checkout@v2


    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck       
 
